services:
  monitor_microservice:
    build:
      context: .
    ports:
      - 8003:8003
    volumes:
      - .:/monitor_microservice
    depends_on:
      db_pg:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "node_health_check"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  pg_data:
    driver: local
  rabbitmq-data:
    driver: local